const express = require('express')
const bodyParser = require('body-parser')
const app = express()
const route = require('./routes/routes.js')
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({extended:true}))

const mongoose = require('mongoose')
mongoose.connect("mongodb+srv://shama_khan:x5nLRtcnPDiTtBGB@cluster0.hb5lr.mongodb.net/shama_main_DB",{useNewUrlParser:true})
.then(()=>console.log("mongodb running perfectly on 27017"))
.catch(err=>console.log(err))
app.use('/',route)
app.listen(process.env.PORT || 3000,function(){
console.log("express running on port"+(process.env.PORT || 3000))
})